### ISSUE TITLE
How do we run the enaml code?

### ISSUE THREAD

**Issue by ceremcem** [codelv/declaracad#17]
How do we run the code? There is no clue in the window menu or in the context menu about how to run the `.enaml` code to generate the model. For example, when I open an example it shows the 3D model. When I select all code and delete, I expect an empty view when I run the code.

**Comment by frmdstryr** [comment]
It re-executes the file whenever a change is made or the active document changes. It's a bit tricky to follow due to viewing in an external process but see [declaracad/editor/plugin.py](https://github.com/codelv/declaracad/blob/master/declaracad/editor/plugin.py#L384), [declaracad/apps/viewer.py](https://github.com/codelv/declaracad/blob/master/declaracad/apps/viewer.py) and [declaracad/occ/view.enaml](https://github.com/codelv/declaracad/blob/master/declaracad/occ/view.enaml#L227)

The views only update a "successfull" render. So an empty file won't trigger an update (as it fails to render anything) but that's a reasonable thing to ask for :+1: .  

You can manually run the standalone viewer with `declaracad view <path/to/yourmodule.enaml>`

**Comment by frmdstryr** [comment]
Sorry, it's not every change, it's every save.

**Comment by ceremcem** [comment]
Would you consider a manual `Run` button somewhere, possibly with a shortcut like `F2` or something?

**Comment by ceremcem** [comment]
...or, maybe change the `Save` menu item as `Save & run`, so `Ctrl+S` will be the shortcut automatically. (I prefer to have an option to run the code without saving (on the fly) though). 

Also, IMO, an empty file should trigger a change, an empty model.

**Comment by frmdstryr** [comment]
Yes, thoughts on just a  "File-> Run"?

**Comment by frmdstryr** [comment]
I pushed an update for this so you can run without saving. 

It could be improved, currently when switching editors it reloads from disk again instead of from any changes in the editor (until run is triggered again).

**Comment by ceremcem** [comment]
Looks very nice, thanks.
